language: node_js
addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
before_script:
  - npm install
  - npm run build:prod
after_success:
  - npm run coverage
  - '.travis/build_docker.sh'
node_js:
  - 'lts/gallium'
sudo: required
notifications:
  slack:
    rooms:
      - jembihealthsystems:mlQYVFbijxcZkesCt7G5VBoM
    on_success: change
    on_failure: always
